[project]
name = "kubenetespractice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyhelm>=2.14.5",
    "protobuf==5.29.4",
    "grpcio-tools==1.71.0",
]
